{% set name = "metabolabpy" %}
{% set version = "0.6.41" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "2f3747617c1c38876ea3606639321083eb63957a64c8bba1b1a191c67f18208c"

build:
  noarch: python
  number: 0
  entry_points:
    - metabolabpy = metabolabpy.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - numpy
    - scipy
    - matplotlib
    - pyside2
    - openpyxl
    - pyautogui
    - qtmodern
    - xlsxwriter

test:
  imports:
    - metabolabpy
    - metabolabpy.nmr
  commands:
    - metabolabpy --help

about:
  home: https://github.com/ludwigc/metabolabpy
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3"
  license_file: LICENSE
  summary: "Python package for data processing of NMR 1D and 2D metabolomics and metabolism tracing data"

extra:
  container:
    extended-base: true
  skip-lints:
    - uses_matplotlib
  recipe-maintainers:
    - RJMW
    - ludwigc
