{% set name = "metabolabpy" %}
{% set version = "0.6.35" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "e4145a44fedd3ac1df591bf511fd3d6a33e10824442f64ba7081a8f0da25ae1a"

build:
  noarch: python
  number: 0
  entry_points:
    - metabolabpy = metabolabpy.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - python >3.7
    - pip
    - xorg-libxfixes  # [linux]
  run:
    - python >3.7
    - numpy
    - scipy
    - matplotlib
    - pyside2
    - openpyxl
    - psutil
    - pyautogui

test:
  imports:
    - metabolabpy
    - metabolabpy.nmr
  commands:
    - metabolabpy --help

about:
  home: https://github.com/ludwigc/metabolabpy
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3"
  license_file: LICENSE
  summary: "Python package for data processing of NMR 1D and 2D metabolomics and metabolism tracing data"

extra:
  container:
    extended-base: true
  skip-lints:
    - uses_matplotlib
  recipe-maintainers:
    - RJMW
    - ludwigc
