{% set name = "IsoQuant" %}
{% set version = "1.3.0" %}
{% set sha256 = "464f36c1d73c101e404e6b314fb0093ba8bf08c28aea80ae72ba5e4862997ca7" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/ablab/IsoQuant/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python
    - argcomplete<=1.11.1
    - argh<=0.26.2
    - biopython<=1.76
    - gffutils<=0.10.1
    - minimap2
    - numpy<=1.18.1
    - pandas<=1.0.1
    - pybedtools==0.8.1
    - pyfaidx<=0.5.8
    - pysam>=0.15
    - samtools==1.10
    - simplejson<=3.17.0
    - six<=1.14.0

test:
  source_files:
    - tests
  commands:
    - isoquant.py --test
    - rm -rf isoquant_test

about:
  summary: IsoQuant is a tool for reference-based analysis of long RNA reads.
  home: https://github.com/ablab/IsoQuant
  license: GPL2
