{% set version = "1.11.0" %}
{% set name = "srnadiff" %}
{% set bioc = "3.13" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: 4f5417e9048c89c6f331f4cd62e57284
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: knitr, rmarkdown, testthat
# SystemRequirements: C++11
requirements:
  host:
    - 'bioconductor-biocparallel >=1.26.0,<1.27.0'
    - 'bioconductor-biocstyle >=2.20.0,<2.21.0'
    - 'bioconductor-deseq2 >=1.32.0,<1.33.0'
    - 'bioconductor-genomeinfodb >=1.28.0,<1.29.0'
    - 'bioconductor-genomicalignments >=1.28.0,<1.29.0'
    - 'bioconductor-genomicfeatures >=1.44.0,<1.45.0'
    - 'bioconductor-genomicranges >=1.44.0,<1.45.0'
    - 'bioconductor-gviz >=1.36.0,<1.37.0'
    - 'bioconductor-iranges >=2.26.0,<2.27.0'
    - 'bioconductor-rsamtools >=2.8.0,<2.9.0'
    - 'bioconductor-rtracklayer >=1.52.0,<1.53.0'
    - 'bioconductor-s4vectors >=0.30.0,<0.31.0'
    - 'bioconductor-summarizedexperiment >=1.22.0,<1.23.0'
    - r-base
    - r-biocmanager
    - r-devtools
    - 'r-rcpp >=0.12.8'
    - libblas
    - liblapack
  run:
    - 'bioconductor-biocparallel >=1.26.0,<1.27.0'
    - 'bioconductor-biocstyle >=2.20.0,<2.21.0'
    - 'bioconductor-deseq2 >=1.32.0,<1.33.0'
    - 'bioconductor-genomeinfodb >=1.28.0,<1.29.0'
    - 'bioconductor-genomicalignments >=1.28.0,<1.29.0'
    - 'bioconductor-genomicfeatures >=1.44.0,<1.45.0'
    - 'bioconductor-genomicranges >=1.44.0,<1.45.0'
    - 'bioconductor-gviz >=1.36.0,<1.37.0'
    - 'bioconductor-iranges >=2.26.0,<2.27.0'
    - 'bioconductor-rsamtools >=2.8.0,<2.9.0'
    - 'bioconductor-rtracklayer >=1.52.0,<1.53.0'
    - 'bioconductor-s4vectors >=0.30.0,<0.31.0'
    - 'bioconductor-summarizedexperiment >=1.22.0,<1.23.0'
    - r-base
    - r-biocmanager
    - r-devtools
    - 'r-rcpp >=0.12.8'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Finding differentially expressed unannotated genomic regions from RNA-seq data'
  description: 'srnadiff is a package that finds differently expressed regions from RNA-seq data at base-resolution level without relying on existing annotation. To do so, the package implements the identify-then-annotate methodology that builds on the idea of combining two pipelines approachs differential expressed regions detection and differential expression quantification.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

