{% set name = "mimseq" %}
{% set version = "0.3.4.3" %}

package:
  name: mimseq
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f09354bde39f52069c1f30205824834619e47a894ba813f18b7f3bd602b8180f

build:
  number: 0
  noarch: python
  entry_points:
    - mimseq = mimseq.mimseq:main
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - r-base 3.6
    - biopython
    - matplotlib-base >=3
    - numpy
    - pandas
    - requests
    - pybedtools
    - pyfiglet
    - pysam
    - seaborn
    - pandas
    - infernal >=1.1.4
    - blast >=2.10
    - gmap 2019.02.26
    - samtools 1.11
    - bedtools
    - r-ggplot2 3.2.1
    - bioconductor-complexheatmap
    - bioconductor-deseq2
    - r-pheatmap
    - r-calibrate
    - r-gridextra
    - r-plyr
    - r-dplyr
    - r-tidyverse
    - r-devtools

test:
  imports:
    - mimseq
  commands:
    - mimseq --help

about:
  home: "https://github.com/nedialkova-lab/mim-tRNAseq"
  license: GPL-3.0-only
  license_family: GPL3
  summary: "Modification-induced misincorporation tRNA sequencing."
