{% set version = "1.0.0" %}
{% set name = "PDATK" %}
{% set bioc = "3.13" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 198476ab068a0ef9cffc927dab0da948
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat (>= 3.0.0), msigdbr, BiocStyle, rmarkdown, knitr, HDF5Array
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.38.0,<0.39.0'
    - 'bioconductor-biocparallel >=1.26.0,<1.27.0'
    - 'bioconductor-consensusclusterplus >=1.56.0,<1.57.0'
    - 'bioconductor-coregx >=1.4.0,<1.5.0'
    - 'bioconductor-genefu >=2.24.0,<2.25.0'
    - 'bioconductor-matrixgenerics >=1.4.0,<1.5.0'
    - 'bioconductor-multiassayexperiment >=1.18.0,<1.19.0'
    - 'bioconductor-piano >=2.8.0,<2.9.0'
    - 'bioconductor-s4vectors >=0.30.0,<0.31.0'
    - 'bioconductor-summarizedexperiment >=1.22.0,<1.23.0'
    - 'bioconductor-survcomp >=1.42.0,<1.43.0'
    - 'bioconductor-switchbox >=1.28.0,<1.29.0'
    - r-base
    - r-caret
    - r-clusterrepro
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-ggplotify
    - r-igraph
    - r-matrixstats
    - r-plyr
    - r-proc
    - r-rcolorbrewer
    - r-reportroc
    - r-rlang
    - r-scales
    - r-survival
    - r-survminer
    - r-verification
  run:
    - 'bioconductor-biocgenerics >=0.38.0,<0.39.0'
    - 'bioconductor-biocparallel >=1.26.0,<1.27.0'
    - 'bioconductor-consensusclusterplus >=1.56.0,<1.57.0'
    - 'bioconductor-coregx >=1.4.0,<1.5.0'
    - 'bioconductor-genefu >=2.24.0,<2.25.0'
    - 'bioconductor-matrixgenerics >=1.4.0,<1.5.0'
    - 'bioconductor-multiassayexperiment >=1.18.0,<1.19.0'
    - 'bioconductor-piano >=2.8.0,<2.9.0'
    - 'bioconductor-s4vectors >=0.30.0,<0.31.0'
    - 'bioconductor-summarizedexperiment >=1.22.0,<1.23.0'
    - 'bioconductor-survcomp >=1.42.0,<1.43.0'
    - 'bioconductor-switchbox >=1.28.0,<1.29.0'
    - r-base
    - r-caret
    - r-clusterrepro
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-ggplotify
    - r-igraph
    - r-matrixstats
    - r-plyr
    - r-proc
    - r-rcolorbrewer
    - r-reportroc
    - r-rlang
    - r-scales
    - r-survival
    - r-survminer
    - r-verification
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Pancreatic Ductal Adenocarcinoma Tool-Kit'
  description: 'Pancreatic ductal adenocarcinoma (PDA) has a relatively poor prognosis and is one of the most lethal cancers. Molecular classification of gene expression profiles holds the potential to identify meaningful subtypes which can inform therapeutic strategy in the clinical setting. The Pancreatic Cancer Adenocarcinoma Tool-Kit (PDATK) provides an S4 class-based interface for performing unsupervised subtype discovery, cross-cohort meta-clustering, gene-expression-based classification, and subsequent survival analysis to identify prognostically useful subtypes in pancreatic cancer and beyond. Two novel methods, Consensus Subtypes in Pancreatic Cancer (CSPC) and Pancreatic Cancer Overall Survival Predictor (PCOSP) are included for consensus-based meta-clustering and overall-survival prediction, respectively. Additionally, four published subtype classifiers and three published prognostic gene signatures are included to allow users to easily recreate published results, apply existing classifiers to new data, and benchmark the relative performance of new methods. The use of existing Bioconductor classes as input to all PDATK classes and methods enables integration with existing Bioconductor datasets, including the 21 pancreatic cancer patient cohorts available in the MetaGxPancreas data package. PDATK has been used to replicate results from Sandhu et al (2019) [https://doi.org/10.1200/cci.18.00102] and an additional paper is in the works using CSPC to validate subtypes from the included published classifiers, both of which use the data available in MetaGxPancreas. The inclusion of subtype centroids and prognostic gene signatures from these and other publications will enable researchers and clinicians to classify novel patient gene expression data, allowing the direct clinical application of the classifiers included in PDATK. Overall, PDATK provides a rich set of tools to identify and validate useful prognostic and molecular subtypes based on gene-expression data, benchmark new classifiers against existing ones, and apply discovered classifiers on novel patient data to inform clinical decision making.'
  license_file: LICENSE

