{% set version = "0.1.3" %}

package:
  name: mwga-utils
  version: {{ version }}

build:
  number: 2
  skip: True  # [osx]

source:
  url: https://github.com/RomainFeron/mgwa_utils/archive/{{ version }}.tar.gz
  sha256: 8e213b97bbb1be437e2438b6208e65fe828095a34b2e54cfbf88089878749fa6

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - stats --help > /dev/null

about:
  home: https://github.com/RomainFeron/mgwa_utils
  license: GPL3
  license_file: LICENSE
  summary: Collection of utilities for processing Multispecies Whole Genome Alignments
